# Generated by Django 5.1.5 on 2025-03-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.IntegerField(default=1)),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='coin',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='name',
        ),
        migrations.AddField(
            model_name='coin',
            name='color',
            field=models.CharField(default='Grey', max_length=16),
        ),
        migrations.AddField(
            model_name='coin',
            name='holo',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
