# Generated by Django 4.2.7 on 2025-03-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.coin')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.player')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='owners',
            field=models.ManyToManyField(through='coin.Collection', to='coin.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.ManyToManyField(through='coin.Collection', to='coin.coin'),
        ),
    ]
