# Generated by Django 4.2.7 on 2025-03-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_coin_num_collection_coin_owners_player_coins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='name',
            new_name='cointype',
        ),
        migrations.RenameField(
            model_name='cointype',
            old_name='value',
            new_name='basevalue',
        ),
    ]
