# Generated by Django 5.1.5 on 2025-03-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_coin_name_alter_cointype_desc_alter_cointype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.cointype'),
        ),
    ]
