# Generated by Django 5.1.5 on 2025-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_alter_coin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointype',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
