# Generated by Django 5.1.5 on 2025-02-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemText', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField(verbose_name='start date')),
                ('dueDate', models.DateTimeField(verbose_name='due date')),
            ],
        ),
    ]
