# Generated by Django 5.1.5 on 2025-02-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemText',
            new_name='text',
        ),
    ]
