# Generated by Django 5.1.5 on 2025-02-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_itemtext_item_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='startDate',
        ),
    ]
