# Generated by Django 5.1.5 on 2025-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_item_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dueDate',
            field=models.CharField(max_length=32),
        ),
    ]
