# Generated by Django 5.1.5 on 2025-02-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time reserved')),
                ('max_people', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=64)),
                ('host_contact', models.CharField(max_length=32)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Culinary.timeslot')),
            ],
        ),
    ]
