# Generated by Django 5.1.5 on 2025-02-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Culinary', '0003_reser_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='t',
            field=models.DateTimeField(),
        ),
    ]
